name: platform
on:
  push:
    branches: [ master ]
jobs:

  setup:
    strategy:
      matrix:
        platform: ["ubuntu-latest"]
        node: [10.x]
    runs-on: ${{ matrix.platform }}
    name: build on node ${{ matrix.node }} ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Download CC Test Reporter"
      run: |
        mkdir -p tmp/
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
        chmod +x ./tmp/cc-test-reporter
    - name: "React Stack"
      run: | 
        cd stacks/react
        npm ci
        npm run coverage 
        ../../tmp/cc-test-reporter format-coverage -t lcov -o ../../tmp/codeclimate.react-stack.json
    - name: "Submit CC coverage"
      run: |
        ../../tmp/cc-test-reporter sum-coverage ../../tmp/codeclimate.*.json -p 1 -o tmp/codeclimate.total.json
        ../../tmp/cc-test-reporter upload-coverage -i ../../tmp/codeclimate.total.json
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}